plugins:
  - stylelint-prettier
  - stylelint-order
  - stylelint-no-unsupported-browser-features
  - stylelint-scss

extends:
  - stylelint-config-standard-scss

customSyntax: "postcss-scss"

rules:
  prettier/prettier: true
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - tailwind
        - apply
        - config
        - variants
        - responsive
        - screen
  scss/load-no-partial-leading-underscore: true
  scss/no-global-function-names: null
  media-feature-range-notation: 'prefix'
  color-hex-length: 'short'
  color-no-invalid-hex: true
  declaration-block-no-duplicate-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-no-redundant-longhand-properties: null
  media-feature-name-no-unknown: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-descending-specificity: null
  property-no-unknown: true
  property-no-vendor-prefix: true
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-colon-notation: 'single'
  selector-pseudo-element-no-unknown:
    [true, { ignorePseudoElements: ['/deep/'] }]
  unit-no-unknown: true
  value-no-vendor-prefix: true
  order/properties-alphabetical-order: true
  order/order:
    [
      'custom-properties',
      'at-rules',
      'at-variables',
      'dollar-variables',
      'declarations',
      { type: 'at-rule', name: 'media' },
      'rules',
      { type: 'at-rule', name: 'at-root' },
    ]
  plugin/no-unsupported-browser-features: [true, { severity: 'warning' }]
  selector-class-pattern: '^.*$'
  scss/at-import-partial-extension: null
  scss/operator-no-newline-after: null
  function-name-case:
    ['lower', { ignoreFunctions: ['/^([a-z][a-z0-9]*)(-[a-z0-9]+)*$/'] }]
  color-function-notation: 'legacy'
  font-family-no-missing-generic-family-keyword: null
  value-keyword-case: ['lower', { camelCaseSvgKeywords: true }]
